### ISSUE TITLE
Directory Issues? Can't run OpenVPN

### ISSUE THREAD

**Issue by whatsnewsisyphus** [Saiyato/volumio-kodi-plugin#12]
When I try to run https://github.com/Zomboided/service.vpn.manager/
I run into openvpn executing issues, looks like some GetDirectory errors in there with kodi being installed in kodi/.kodi and such. Pretty sure it's a path issue, maybe not running true paths. ( a lot of CPythonInvoker(8): Script invoked without an addon. )

**Comment by Saiyato** [comment]
Does it work if you install vanilla Kodi on a vanilla Jessie image?

**Comment by whatsnewsisyphus** [comment]
Yes, absolutely. Also works on Max2play (which is based on jessie). I tried installing openvpn through ssh and make the vpn manager run sudo vpn pathless, but no go. I also tried forcing it to write logs in the kodi log directory, but no go there either (thought maybe it was getting the wrong root path variable and then trying to write into a log directory under root where it has no permissions or something along that line)

**Comment by whatsnewsisyphus** [comment]
Here is how it gets its log path, and how it gets to openvpn if that helps.

**Log file**
```
def getVPNLogFilePath():
    # Return the full filename for the VPN log file
    # It's platform dependent, but can be forced to the Kodi log location
    use_kodi_dir = xbmcaddon.Addon("service.vpn.manager").getSetting("openvpn_log_location")
    p = getPlatform()
    if p == platforms.WINDOWS or use_kodi_dir == "true" :
        # Putting this with the other logs on Windows
        return xbmc.translatePath("special://logpath/openvpn.log")
    if p == platforms.LINUX or p == platforms.RPI:
        # This should be a RAM drive so doesn't wear the media
        return "/run/openvpn.log"
        
    # **** ADD MORE PLATFORMS HERE ****
    
    return ""
```

**OpenVPN path**

```
def getOpenVPNPath():
    # Call the platform VPN to start the VPN
    #if fakeConnection():
    #    p = platforms.LINUX
    #else:
    p = getPlatform()   
    if p == platforms.RPI:
        return getAddonPath(False, "network.openvpn/bin/openvpn")
    if p == platforms.LINUX:
        if xbmcaddon.Addon("service.vpn.manager").getSetting("openvpn_no_path") == "true": return "openvpn"
        return "/usr/sbin/openvpn"
    if p == platforms.WINDOWS:
        # No path specified as install will update command path
        return "openvpn"
        
    # **** ADD MORE PLATFORMS HERE ****
    
    return
```

**Comment by Saiyato** [comment]
The symlink I create is on OS level, meaning only the OS knows it's not the real path. Any software running on top of the OS should regard the symlink as the absolute location, the OS will in turn redirect the cursor to the linked location.

Can you provide me with the details of how you installed the VPN manager (step by step please)? This will save me some time trying to set it up exactly like you did (and might help other people).

I can only guess what is possibly going wrong, I think you are running the VPN manager under a different user than Kodi. Doing so will prevent the user to access the Kodi-specific folders (a rights issue) I presume. But I need to see it for myself to confirm.

I am really interested in the VPN option, but I haven't got much time to read into the matter right now, so I placed it on hold... ;)

Thanks in advance.

**Comment by whatsnewsisyphus** [comment]
Hello again. I follow the [wiki](https://github.com/Zomboided/service.vpn.manager/wiki/01.-Installation) on the installation

1. I download the repo zip and throw it on volumio using SFTP
2. I use install addon from zip file to navigate to home/volumio and install the said zip
3. I grab the VPN plugin from the newly installed repo
4. I use the wizard/enter manually my VPN detail, and select Log into the kodi folder (because I am not sure whether it would have the permissions to be writing into its own space in ramdisk, but it fails before it gets here)

**Comment by whatsnewsisyphus** [comment]
Just wanted to say hello and ask if you had any chance of looking into this.

**Comment by Saiyato** [comment]
Yeah, but I don't have a VPN account to test with.

Have you read this: https://github.com/Zomboided/service.vpn.manager/wiki/07.-Debug-Options#always-use-kodi-log-directory-for-openvpn-log

**Comment by whatsnewsisyphus** [comment]
Yeah I've tried that to no avail

**Comment by ThaDaVos** [comment]
Is this fixed? This is currently stopping me from combining my audio pi with my beefier kodi machine

**Comment by Saiyato** [comment]
I guess not, the log gives me the following "sudo: no tty present and no askpass program specified", which leads to believe it's a rights issue. The plugin is giving me all kinds of errors that it needs to perform certain commands. Is it really the only reliable VPN plugin, which is blocking your usage?

**Comment by ThaDaVos** [comment]
Strange... but yes, it's the only reliable VPN add-on for Kodi to manage OpenVPN (which also have to be installed in the linux)

**Comment by Saiyato** [comment]
Found it! The problem is administrator rights, it has nothing to do with Kodi, other than that when it runs as admin, it works perfectly. I'm not going to do this, as this poses a potential (unnecessary) risk.

Try disabling sudo and move the log to the kodi directory.

You can find this here: https://github.com/Zomboided/service.vpn.manager/wiki/01.-Installation
Look for: "For all non LE/OE Linux platforms"
