### ISSUE TITLE
Keymap usage

### ISSUE THREAD

**Issue by Chris0706** [Saiyato/volumio-kodi-plugin#14]
Hello Saiyato,

first of all, thanks for the great work of bringing Kodi to Volumio! After getting everything ready to go, I am still wondering how to use a custom keymap for Kodi, as I use a special remote.
I got a keymap, which works fine on a LibreELEC installation, but I can figure out, how it can be loaded in with Volumio and Kodi.
I started by putting it in the /usr/bin/kodi-standalone/userdata/keymaps, where it works for LibreELEC. But it doesnt seem to load it while starting. I made sure to chown kodi:kodi and chmod 777 it :/
Maybe that is the wrong folder for the settings? Kodi uses ~/home/.kodi/userdata normally, but that isn't present in your installation.

Best regards
Chris

**Comment by Saiyato** [comment]
Hi Chris,

I think you should put the keymap in `/home/kodi/.kodi/userdata/keymaps` which is symlinked to `/data/configuration/miscellanea/Kodi/Configuration/userdata`.

So I think you should paste your keymaps there. Let me know if that helps.

Cheers

**Comment by Chris0706** [comment]
Hm, I already found my file there, too. Chaning ownership from kodi to volumio didn't do the trick either. Will try the Keymap Editor Addon for Kodi now :/

Edit: Okay i changed it with Keymap Editor. Funny enough THAT didn't work on LibreELEC :X
