### ISSUE TITLE
GUI not starting

### ISSUE THREAD

**Issue by teq0** [Saiyato/volumio-kodi-plugin#17]
I have Kodi fully installed and everything was working fine (and thanks for your work!).

I was working on a [Volumio PR](https://github.com/volumio/Volumio2/pull/1435) and I'm not sure what I did but now the GUI doesn't start at boot, I just get the console login prompt. Any ideas where I can look?

**Comment by Saiyato** [comment]
Hi,

What GUI are you talking about? And what did you do on which platform?

**Comment by teq0** [comment]
I meant the Raspberry Pi GUI. Never mind, I had broken the whole thing, the Volumio git repo was corrupted. I've re-imaged the machine from scratch, all good now, thanks.

**Comment by Saiyato** [comment]
Hahaha ok, check, glad it's working now. :)
Remember to either pull this plugin from GH or patch the UIConfig as mentioned in #18

**Comment by teq0** [comment]
It's actually in the official list in the latest release.

**Comment by Saiyato** [comment]
Found the problem... the video devices change ownership on boot. Will create an issue on Volumio.

Update: scratch that last part, I can work around it, the 10-permission rules file can be empty after installation. Will investigate...

**Comment by Saiyato** [comment]
Update2: you have to wait the full install, if you cancel halfway through... You have to start over.
This is possible if a GUI error occurs, you have to wait it out.

**Comment by teq0** [comment]
Thanks for looking into it, I'm all good, I did a fresh install and it's fine. I don't expect many people to have the same problem I had, I had corrupted my Volumio install with some bad git commands.
