### ISSUE TITLE
Unable to save settings in Kodi plugin

### ISSUE THREAD

**Issue by xenixesa** [Saiyato/volumio-kodi-plugin#18]
Hi Saiyato,
first thanks for your work, if I can get my RPi 3 + Volumio + Kodi to work over Hifiberry amp life will be good! 
However I cannot save settings in the plugin settings page. Hitting Save gives no reaction.
I tried reinstall, Chrome, Firefox and Vivaldi browsers on both ubuntu and windows computers and even with the official Volumio app. I tried uninstalling and reinstalling, no luck.
I even tried to change the settings in the json file but that didn't work and reached the limits of my linux :)

**Comment by Saiyato** [comment]
This is a known problem, will be fixed when my PR is merged into Volumio.

Workaround is:
```
sudo mv /data/plugins/miscellanea/kodi/UIconfig.json /data/plugins/miscellanea/kodi/UIConfig.json
systemctl restart volumio
```

See: https://github.com/volumio/volumio-plugins/pull/151

**Comment by xenixesa** [comment]
thanks that worked perfectly! sorry I missed it.

**Comment by Saiyato** [comment]
No problem ;) glad it worked out for you
