### ISSUE TITLE
Freezing Video on Kodi

### ISSUE THREAD

**Issue by biva** [Saiyato/volumio-kodi-plugin#21]
Thank you very much for your plugin, it's working great on RPI3. But with HD video, I've got freeze/hang and it's impossible to watch the video. 

Should I increase the memory reserved for GPU (it's 256 for now)? Disable the Webserver?

Any other idea?

Config: RPI3 + Allo Boss DAC + Allo Volt Amp
Volumio 2.389

**Comment by biva** [comment]
Any idea? Thanks!

**Comment by Saiyato** [comment]
Hi there,

In my tests I did not experience the above behavior. What kind of file did you play? I'm especially interested in the size, codec used and if it's MPEG2/VC1, which can be used with hardware decoding. Finally what kind of audio stream is embedded?

Also, are you using a fileshare or streaming services? In the case of a fileshare, is it NFS or SMB and does it help to switch between those?

As for the memory for video playback, I've been able to play (up to) 15GB h.264 rips with DTS  sound (TrueHD did expose some decoding problems), played from both SMB and NFS shares, the latter did perform better though.

**Comment by biva** [comment]
Thanks @Saiyato 

That's a .m2ts recorded on Arte with a Freebox Revolution: 1.19 GB, 1080×1440. And that what's VLC tells me:
![image](https://user-images.githubusercontent.com/9964305/44653537-5568a780-a9ef-11e8-8c55-52cbf09e6861.png)

This is a fileshare, I think SMB (how can I verify it?). How can I change between those? RPI3 is on Wifi and the server is on ethernet.

**Comment by biva** [comment]
Does it give you any hint?

**Comment by Saiyato** [comment]
Hi,

I've been away quite a lot, so haven't been able to test. The extension m2ts does imply an mpeg-2 stream, which CPU heavy, even for a Pi2/3. Please see: https://discourse.osmc.tv/t/problem-playing-m2ts-1080-50p/7464

If you re-encode it to h.264 in an mkv container, does that solve your problem? If so, then try installing the mpeg-2 license (only costs a few bucks).

If converting helps, then that confirms that the decoding of the video on CPU was problematic. The license will enable hardware decoding on the GPU. Increasing the memory will then most certainly not benefit you. At least, not in the sense that it will improve playback.

**Comment by biva** [comment]
Thanks @Saiyato , I'll try. But then, why is VLC saying that the codec is H264 MPEG-4?

**Comment by Saiyato** [comment]
I'm not sure why VLC would say that, and it can still be MPEG-4; although all the evidence points in another direction: https://en.wikipedia.org/wiki/.m2ts

It could also be a bug in VLC or the format to which VLC converts it for playback. I'm no expert on codecs, so I can't answer that for you ;)

**Comment by Saiyato** [comment]
Any news on the above? I just benchmarked a h.264 1080p file (size: 20GB); there were no hiccups whatsoever. It played from an NFS share over the network (wired).

**Comment by biva** [comment]
Hello @Saiyato 
It appears that the problem was... the wifi. I just put the RPI on ethernet and it works perfectly. The WiFi on the RPI is really bad :( (I'm sure it comes from the RPI because VLC and MPC-HC on my computer over Wifi don't have any issue to read the video.

Now I have another problem: subtitles with MKV. But I created a new issue for this: https://github.com/Saiyato/volumio-kodi-plugin/issues/27
