### ISSUE TITLE
Kodi display question

### ISSUE THREAD

**Issue by gotrune** [Saiyato/volumio-kodi-plugin#24]
Hello, 
I've recently buy a Raspberry Official LCD and i would know if its possible to have kodi on the HDMI output and the TouchDisplay plugin on the Raspberry Official LCD.
Any chance of that?
Thank for all

**Comment by Saiyato** [comment]
I have no clue whatsoever, but I don't think it will work, because Kodi will probably default to the "main" screen, which is the LCD when connected.
