### ISSUE TITLE
no sound with usb out and external DAC (myDac micromega)

### ISSUE THREAD

**Issue by LeBubar** [Saiyato/volumio-kodi-plugin#26]
bonjour,
I use Kodi over volumio on my Rasp with a external dac (with usb port of the raspberry).
my problem : 
I  listen the music under volumio. work fine.  (choose DAC USB output in parameter).
I listen the music under kodi.work fine (choose DAC USB output in kodi parameter)
there no sound when I modifie the sound output in kodi to BCM2835 ALSA.

if I use the jackOut out HDMI out in volumio : with this configuration (kodi out to BCM2835 ALSA) I hear the music.

I can't solve the problem : pilot my music server with Kodi over volumio with my DAC . 
thank for help . Merci # #

**Comment by Saiyato** [comment]
Hi there,

I'm not sure I understand what you want to achieve here? You want Volumio to play over the soundcard, but Kodi to play sound over the HDMI port?
