### ISSUE TITLE
No subtitle with MKV

### ISSUE THREAD

**Issue by biva** [Saiyato/volumio-kodi-plugin#27]
Hello,
I can't display the subtitles when playing a MKV file. I see on Google that it's probably related to `libass5` but I'm not skilled enough to understand why.

I tried `sudo apt-get install libass5` but it doesn't want to install on volumio. Some other threads advise to do `sudo apt-get install libass-dev` but it doesn't want to install either.

Some threads I read:
- https://forum.kodi.tv/showthread.php?tid=310750
- https://discourse.osmc.tv/t/local-subtitles-not-displayed-while-playing-mkv-file/760/5
- https://www.reddit.com/r/raspberry_pi/comments/2vmowu/subtitles_not_displaying_on_mkv_files_raspberry/

**Comment by Saiyato** [comment]
Are these subtitles embedded, or just srt files next to the video file?

**Comment by Saiyato** [comment]
Or maybe even downloaded subtitles from sites like subscene/podnapisi etc.

**Comment by biva** [comment]
Thanks @Saiyato 
Subtitles are embedded. I know I can download other subtitles, but it's an additional step.
What do you think about the `libass5` issue mentioned above?
Thanks again :)

**Comment by Saiyato** [comment]
I'll have to rebuild my old environment, we're renovating the house so all lab equipment has been stowed away. I don't expect to be able to test it in the near future, but I'll be sure to test it. ;)

As for the library, it does make sense: https://packages.ubuntu.com/xenial/libass5
I quote: "library for SSA/ASS subtitles rendering", so it could very well be the case.

Just did a quick test on my main Volumio instance (not too smart, but you've live a little, right?) and it succeeded the first time:

```
volumio@volumiomain:~$ sudo apt-get install libass5
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libenca0 libfribidi0
The following NEW packages will be installed:
  libass5 libenca0 libfribidi0
0 upgraded, 3 newly installed, 0 to remove and 146 not upgraded.
Need to get 151 kB of archives.
After this operation, 411 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.raspbian.org/raspbian/ jessie/main libenca0 armhf 1.16-1 [55.3 kB]
Get:2 http://archive.raspbian.org/raspbian/ jessie/main libfribidi0 armhf 0.19.6-3 [43.2 kB]
Get:3 http://archive.raspbian.org/raspbian/ jessie/main libass5 armhf 0.10.2-3 [52.4 kB]
Fetched 151 kB in 0s (487 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libenca0:armhf.
(Reading database ... 25164 files and directories currently installed.)
Preparing to unpack .../libenca0_1.16-1_armhf.deb ...
Unpacking libenca0:armhf (1.16-1) ...
Selecting previously unselected package libfribidi0:armhf.
Preparing to unpack .../libfribidi0_0.19.6-3_armhf.deb ...
Unpacking libfribidi0:armhf (0.19.6-3) ...
Selecting previously unselected package libass5:armhf.
Preparing to unpack .../libass5_0.10.2-3_armhf.deb ...
Unpacking libass5:armhf (0.10.2-3) ...
Setting up libenca0:armhf (1.16-1) ...
Setting up libfribidi0:armhf (0.19.6-3) ...
Setting up libass5:armhf (0.10.2-3) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
```

What is your platform again? And which versions are you running?

**Comment by Saiyato** [comment]
I did a fresh install on a vanilla 2.555 image on a Pi2 and I was able to switch between embedded subtitles. What did you do exactly?

**Comment by biva** [comment]
I did `sudo apt-get install libass5` and I receive this message:
<pre><code>You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libass5 : Depends: libenca0 (>= 1.9) but it is not going to be installed
           Depends: libfontconfig1 (>= 2.11) but it is not going to be installed
           Depends: libfreetype6 (>= 2.3.5) but it is not going to be installed
           Depends: libfribidi0 (>= 0.19.2) but it is not going to be installed
           Depends: libharfbuzz0b (>= 0.9.4) but it is not going to be installed
 libc6 : Depends: libgcc1 but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
</code></pre>

Maybe related to the fact that I can't install chromium either, with similar error message: https://github.com/volumio/Volumio2/issues/1592

**Comment by Saiyato** [comment]
Hi @biva it looks like a localised problem, can you share your specs please? What platform and version of Volumio are you using?

**Comment by biva** [comment]
Thanks @Saiyato 
I'm using RPI3 with Allo Boss DAC and Allo Volt amp. Volumio is updated to the last version 2.565
Plugins installed (all to the last available version):
- Kodi Krypton
- Podcast
- Spotify
- Volumio Spotify connect
- Youtube playback
- GPIO buttons

**Comment by Saiyato** [comment]
Can't reproduce this problem, running the latest version of the Kodi plugin and the latest version of Volumio. Baked in subs and downloaded subs are working.
