### ISSUE TITLE
The save button of the settings of the Kodi plugin does not work

### ISSUE THREAD

**Issue by emanuele** [Saiyato/volumio-kodi-plugin#28]
First of all, thank you for the plugin!

On RPi3, from Volumio v2.522 on, the save button of the settings of the Kodi plugin does not work and the options cannot be saved, like "memory reserved for GPU" or "Enable DAC Output for Kodi", etc.. Notice that this problem was documented in the past, see https://volumio.org/forum/plugin-kodi-save-buttons-without-function-t9075.html, but then it was solved. I have other Volumio boxes with a less recent version of Volumio and the problem with the Kodi plugin does not occur.

Other plugins are unaffected, like the Youtube Playback plugin.

In these days, I updated to v.2555 and experienced the same issue.

**Comment by Saiyato** [comment]
Which version of the plugin are you using? Maybe some PR failed.

**Comment by emanuele** [comment]
I'm using the one that automatically comes from the web interface of
Volumio. Later today I will be able to reach that Volumio/RPi box and tell
you more about it.

**Comment by emanuele** [comment]
The version of the volumio-kodi-plugin currently installed on my Volumio/RPi box is 2.2.11.

**Comment by emanuele** [comment]
I've just reinstalled the Volumio/RPi box from scratch, using Volumio 2.565 which provides the volumio-kodi-plugin (Kodi Krypton) v2.2.11. As before, the save button of the settings of the plugin does not work.

**Comment by emanuele** [comment]
Important update: I've just removed the non-working plugin from Volumio and installed the volumio-kodi-plugin from this repository, instead of relying on the one automatically provided by Volumio. I've used volumio_installer.sh in the current master branch. The installation of the plugin went well and the save button now correctly works: I can get the audio from DAC+AMP. Excellent!
I expected that Volumio to provide the same version of the plugin as the one in this repository but, apparently, it is not.

**Comment by Saiyato** [comment]
I just installed a new instance and installed the plugin from the store, the problem is that the store version contains a wrong UIconfig file (note the small letter C) and a correct one, this conflicts. I will see if I can have it removed by PR-ing again.

**Comment by Saiyato** [comment]
Note: this is something that went wrong in merging my latest version, so its a merge conflict rather than a bug.

**Comment by Saiyato** [comment]
See this PR: https://github.com/volumio/volumio-plugins/pull/314

**Comment by nicosea** [comment]
> Important update: I've just removed the non-working plugin from Volumio and installed the volumio-kodi-plugin from this repository, instead of relying on the one automatically provided by Volumio. I've used volumio_installer.sh in the current master branch. The installation of the plugin went well and the save button now correctly works: I can get the audio from DAC+AMP. Excellent!
> I expected that Volumio to provide the same version of the plugin as the one in this repository but, apparently, it is not.

How did you install the plugin manually? Could you copy and paste all the instructions? I cannot do that :-(

**Comment by Saiyato** [comment]
The new version is merged, will check tonight!

**Comment by emanuele** [comment]
Thanks a lot for your work!

**Comment by Saiyato** [comment]
Hi there,

The latest version should be merged now, no need to work around it anymore.

Cheers!

**Comment by emanuele** [comment]
Excellent! Thanks!
