### ISSUE TITLE
Support for Raspberry Pi 4B / blank screen

### ISSUE THREAD

**Issue by tylaro** [Saiyato/volumio-kodi-plugin#30]
I love your plugin and have been using it on a Raspberry Pi 2 B for years. Thank you! 

Now I tried to use the plugin on a Model 4 B on a fresh Volumio 2.609. Installation via Volumio plugin manager runs without errors, but when I activate it I only receive a blank screen. 

I did two fresh installs, several reboots, enabling, disabling, reallocation of memory. 

Are there any workarounds that I could try or plans on supporting the Raspberry 4 B in the future? Please let me know if I can help supplying logs or trying something.

**Comment by xrischan** [comment]
I too am having the same issue. been through what tylaro has done. Even installed older zip versions through the back end (as drag and drop zips are now gone).
What could be causing the black screen?

**Comment by Saiyato** [comment]
Hi there, 

I can't solve this, Kodi on the RPI4 is only compiled for Buster and since Volumio still runs on Jessie, this will not compute.

You should see the login prompt though, not a blank screen. Can you confirm this?

**Comment by xrischan** [comment]
Hi. The terminal is not present after Kodi loads up.
In the mean time I have had to go with LibreElecs latest Kodi.
Hoping I can find a way of putting volumio drivers/codecs over as it doesn't sound anywhere near as good. 
Latest Kodi has DRM as well so netflix and the likes work well. 
So I'm torn untill anyone can make an up-to-date Kodi plugin for volumio.
Thanks All

**Comment by Saiyato** [comment]
Hi,

You'll need someone willing to compile it against Jessie instead of Buster; that'll be your biggest challenge. As far as I know Leia wasn't even compiled for Jessie, it started with Stretch.

I'll close this issue, because it has nothing to do with the plugin or the installation scripts, but the availability of the software itself. ;)

**Comment by xrischan** [comment]
Oh ok.
So it's not considered as a problem then?

**Comment by Saiyato** [comment]
Hi there, it's definitely a problem, just not one I can solve unfortunately. I'll raise the question at the Volumio forum regarding the distro, it's just software on an old distro on new hardware that causes problems ;)

**Comment by Saiyato** [comment]
Update: they're working on it: https://github.com/volumio/Build/issues/388

**Comment by xrischan** [comment]
Excellent. Thanks for your time.
