### ISSUE TITLE
Kodi slow to start

### ISSUE THREAD

**Issue by jmtcreis** [Saiyato/volumio-kodi-plugin#32]
After update Volumio to version 2.698 Kodi takes around 3 minutes to boot.

Is there any way to speed it up?

Thanks in advance for any help.

**Comment by Saiyato** [comment]
Hi, did you upgrade Volumio after installing Kodi?

The fix is installing rtkit, not sure why it broke when upgrading my Volumio installation.

**Comment by Saiyato** [comment]
Just tested a fresh install on the latest version, this seems to work. So upgrading breaks the installation, not much I can do I'm afraid. Installing rtkit solves the issue, so it seems it's deleted somehow. Maybe related to some PulseAudio changes?
