### ISSUE TITLE
avoiding custom repo additions

### ISSUE THREAD

**Issue by macmpi** [Saiyato/volumio-kodi-plugin#6]
Hi,

Looking at various of the `install.sh` scripts (like [this](https://github.com/Saiyato/volumio-kodi-plugin/blob/master/install_rc1.sh#L12-L16)), it shown they do install some custom repositories permanently on Volumio distribution.
Those repositories might have many other binaries, which may happen to take priority over genuine ones in other future (and unrelated) software installs by users.

How about just picking the very specific package needed by this plugin with a `wget` command, and then installing `.deb` package?
Installing a repo (which anyway seems specific for each version) does not really seem to bring benefit for Kodi install in the future, and may rather open a can of worms for users...

Thanks for consideration

**Comment by Saiyato** [comment]
Aye, will check if all dependencies are met without adding the ppa. I'll have to investigate.

**Comment by Saiyato** [comment]
Initial research proves that a repo might be necessary for all dependencies (quite a lot). Still investigating possibilities, this may take a while though. 

What I can do now is remove the repo after installation.

**Comment by macmpi** [comment]
Thanks for your continued investigations.
Indeed, removing the repo (and maybe clearing apt cache then) can provide a nice workaround for now.

**Comment by Saiyato** [comment]
Will try to remove the repo this week. I will also abandon the other repo's (the BETA and Jarvis), which will result in only one install.sh (also easier to maintain).

I've been reading into compiling Kodi myself for quite some time now, to no avail unfortunately. The next step was checking whether I could incorporate the deb-package, but that too didn't work.

Maybe someone with a little bit more Linux experience can look into this? :) Cmake and make/checkinstall are really a bridge too far at this point for me. I don't really understand what it does, so I might need to start from the beginning by reading into compiling for Linux. But that's for another day... ;)

**Comment by Saiyato** [comment]
Update the installation script to remove the archive/repository/ppa and cleanup the package list.

**Comment by macmpi** [comment]
Thanks!
May you remove the unnecessary repo key too?

**Comment by Saiyato** [comment]
Oh yes, totally forgot, will remove that too! :)

Still figuring out how github links issues to commits, and how they relate to milestones. So that info might not be up to par. Sorry for that.

**Comment by Saiyato** [comment]
New commit: 3c0ca07

The key is now removed as well, tested on rPi3, will test on 2 and 1 later this week

**Comment by macmpi** [comment]
Thanks!
